# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.prompt_label = QtWidgets.QLabel(self.centralwidget)
        self.prompt_label.setGeometry(QtCore.QRect(20, 30, 131, 41))
        self.prompt_label.setObjectName("prompt_label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 40, 161, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 300, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.name_list = QtWidgets.QGroupBox(self.centralwidget)
        self.name_list.setGeometry(QtCore.QRect(20, 110, 171, 161))
        self.name_list.setTitle("")
        self.name_list.setObjectName("name_list")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.name_list)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_1 = QtWidgets.QRadioButton(self.name_list)
        self.name_1.setText("")
        self.name_1.setObjectName("name_1")
        self.verticalLayout.addWidget(self.name_1)
        self.name_2 = QtWidgets.QRadioButton(self.name_list)
        self.name_2.setText("")
        self.name_2.setObjectName("name_2")
        self.verticalLayout.addWidget(self.name_2)
        self.name_3 = QtWidgets.QRadioButton(self.name_list)
        self.name_3.setText("")
        self.name_3.setObjectName("name_3")
        self.verticalLayout.addWidget(self.name_3)
        self.name_4 = QtWidgets.QRadioButton(self.name_list)
        self.name_4.setText("")
        self.name_4.setObjectName("name_4")
        self.verticalLayout.addWidget(self.name_4)
        self.name_5 = QtWidgets.QRadioButton(self.name_list)
        self.name_5.setText("")
        self.name_5.setObjectName("name_5")
        self.verticalLayout.addWidget(self.name_5)
        self.user_info = QtWidgets.QLabel(self.centralwidget)
        self.user_info.setGeometry(QtCore.QRect(20, 80, 54, 12))
        self.user_info.setText("")
        self.user_info.setObjectName("user_info")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(290, 40, 75, 23))
        self.submitButton.setObjectName("submitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "音乐播放器"))
        self.prompt_label.setText(_translate("MainWindow", "请输入歌名:"))
        self.lineEdit.setText(_translate("MainWindow", "123"))
        self.submitButton.setText(_translate("MainWindow", "提交"))
